# Generated by Django 3.2.25 on 2024-10-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='called_count',
            field=models.IntegerField(default=0),
        ),
    ]
