# Generated by Django 3.2.25 on 2024-10-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_student_called_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='protected',
            field=models.BooleanField(default=False),
        ),
    ]
